services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    depends_on:
      database:
        condition: service_healthy
  database:
    build:
      context: .
      dockerfile: database.Dockerfile
    restart: always
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - database-volume:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "psql -d $${POSTGRES_DB} -U $${POSTGRES_USER} -c 'SELECT * FROM mineros_init' || exit 1"]
      interval: 5m
      retries: 0
volumes:
  database-volume: