services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file: .env
    depends_on:
      betaso-database:
        condition: service_healthy
      mineros-database:
        condition: service_healthy
  betaso-database:
    build:
      context: .
      dockerfile: betaso-database.Dockerfile
    restart: always
    ports:
      - ${BETASO_PGPORT}:${BETASO_PGPORT}
    volumes:
      - betaso-database-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${BETASO_POSTGRES_USER}
      - POSTGRES_PASSWORD=${BETASO_POSTGRES_PASSWORD}
      - POSTGRES_DB=${BETASO_POSTGRES_DB}
      - PGPORT=${BETASO_PGPORT}
    healthcheck:
      test: ["CMD-SHELL", "psql -d $${BETASO_POSTGRES_DB} -U $${BETASO_POSTGRES_USER} -c 'SELECT * FROM betaso_init' || exit 1"]
      interval: 5m
      retries: 0
  mineros-database:
    image: postgres:alpine
    restart: always
    ports:
      - ${MINEROS_PGPORT}:${MINEROS_PGPORT}
    volumes:
      - mineros-database-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${MINEROS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${MINEROS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${MINEROS_POSTGRES_DB}
      - PGPORT=${MINEROS_PGPORT}
    healthcheck:
      test: ["CMD-SHELL", "psql -d $${MINEROS_POSTGRES_DB} -U $${MINEROS_POSTGRES_USER} -c 'SELECT 1' || exit 1"]
      interval: 5m
      retries: 0
volumes:
  betaso-database-volume:
  mineros-database-volume: