services:
  mineros-backend:
    build:
      context: .
      args:
        - APP_PORT=${APP_PORT}
    depends_on:
      mineros-database:
        condition: service_healthy
    ports:
      - target: ${APP_PORT}
        published: ${APP_PORT}
    env_file:
      - .env
  mineros-database:
    image: postgres:latest
    restart: always
    ports:
      - target: ${PGPORT}
        published: ${PGPORT}
    volumes:
      - mineros-volume:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
volumes:
  mineros-volume: